### ISSUE TITLE
OSM - Input Styles prevent usage of TinyMCE Fields

### ISSUE THREAD

**Issue by schrittweiter** [mcguffin/acf-field-openstreetmap#76]
A bug has sneaked into the last version, which prevents the use of TinyMCE fields in ACF blocks. The CSS property must refer to the OSM field type.

```css
.acf-block-preview iframe {
    pointer-events: none;
}
```

Best regards
David
